
------------ LOG FILE | 31/03/2022 - 03:17:48 ------------
[03:17:48] - INFO - monitor 1 (15160) criado!

------------ LOG FILE | 31/03/2022 - 08:53:52 ------------
[08:53:52] - INFO - monitor 1 (16480) criado!
[08:53:52] - WARNING - monitor 1 (Traceback (most recent call last):
  File "c:\Users\henri\Documents\GitHub\S2SLauncher\application.py", line 171, in monitor_manager
    if driver.current_url == blocked or not driver.current_url == application_url:
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 915, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=100.0.4896.60)
Stacktrace:
Backtrace:
	Ordinal0 [0x00E07413+2389011]
	Ordinal0 [0x00D99F61+1941345]
	Ordinal0 [0x00C8C520+836896]
	Ordinal0 [0x00C80682+788098]
	Ordinal0 [0x00C80EB8+790200]
	Ordinal0 [0x00C82752+796498]
	Ordinal0 [0x00C7C0D9+770265]
	Ordinal0 [0x00C8D9D0+842192]
	Ordinal0 [0x00CE3AE2+1194722]
	Ordinal0 [0x00CD3F66+1130342]
	Ordinal0 [0x00CAE546+976198]
	Ordinal0 [0x00CAF456+980054]
	GetHandleVerifier [0x00FB9632+1727522]
	GetHandleVerifier [0x0106BA4D+2457661]
	GetHandleVerifier [0x00E9EB81+569713]
	GetHandleVerifier [0x00E9DD76+566118]
	Ordinal0 [0x00DA0B2B+1968939]
	Ordinal0 [0x00DA5988+1989000]
	Ordinal0 [0x00DA5A75+1989237]
	Ordinal0 [0x00DAECB1+2026673]
	BaseThreadInitThunk [0x7605FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77CD7A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77CD7A4E+238]

)
