
------------ LOG FILE | 09/05/2022 - 12:25:19 ------------
[12:25:19] - INFO - monitor 1 (2660) initialized!
[12:25:19] - WARNING - monitor 1 (Traceback (most recent call last):
  File "c:\Users\henri\Documents\GitHub\S2SLauncher\frontend\FxWebLauncher.py", line 176, in monitor_manager
    if driver.current_url == blocked or not driver.current_url == application_url:
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 920, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x0065B8F3+2406643]
	Ordinal0 [0x005EAF31+1945393]
	Ordinal0 [0x004DC748+837448]
	Ordinal0 [0x004C42B0+737968]
	Ordinal0 [0x00526C09+1141769]
	Ordinal0 [0x00533E22+1195554]
	Ordinal0 [0x00524096+1130646]
	Ordinal0 [0x004FE636+976438]
	Ordinal0 [0x004FF546+980294]
	GetHandleVerifier [0x008C9612+2498066]
	GetHandleVerifier [0x008BC920+2445600]
	GetHandleVerifier [0x006F4F2A+579370]
	GetHandleVerifier [0x006F3D36+574774]
	Ordinal0 [0x005F1C0B+1973259]
	Ordinal0 [0x005F6688+1992328]
	Ordinal0 [0x005F6775+1992565]
	Ordinal0 [0x005FF8D1+2029777]
	BaseThreadInitThunk [0x7584FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77877A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77877A4E+238]

)

------------ LOG FILE | 09/05/2022 - 12:28:06 ------------
[12:28:06] - WARNING - monitor 1 (Traceback (most recent call last):
  File "c:\Users\henri\Documents\GitHub\S2SLauncher\frontend\FxWebLauncher.py", line 151, in monitor_manager
    driver.get(application_url)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 442, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Users\henri\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=101.0.4951.54)
Stacktrace:
Backtrace:
	Ordinal0 [0x0065B8F3+2406643]
	Ordinal0 [0x005EAF31+1945393]
	Ordinal0 [0x004DC610+837136]
	Ordinal0 [0x004D0442+787522]
	Ordinal0 [0x004D0C78+789624]
	Ordinal0 [0x004D24B2+795826]
	Ordinal0 [0x004CBF09+769801]
	Ordinal0 [0x004DDAC0+842432]
	Ordinal0 [0x00533E62+1195618]
	Ordinal0 [0x00524096+1130646]
	Ordinal0 [0x004FE636+976438]
	Ordinal0 [0x004FF546+980294]
	GetHandleVerifier [0x008C9612+2498066]
	GetHandleVerifier [0x008BC920+2445600]
	GetHandleVerifier [0x006F4F2A+579370]
	GetHandleVerifier [0x006F3D36+574774]
	Ordinal0 [0x005F1C0B+1973259]
	Ordinal0 [0x005F6688+1992328]
	Ordinal0 [0x005F6775+1992565]
	Ordinal0 [0x005FF8D1+2029777]
	BaseThreadInitThunk [0x7584FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77877A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77877A4E+238]

)
